#!/bin/bash
tail -n +2 | cut -f -1 | sort -k 1 | uniq -c | sort -rnk 1 | head -n 11 | rev | cut -d ' ' -f -1 | rev # cut -f2 -d$'\t' -f 1 | sort | uniq -c | LC_ALL=C sort -rf | head -n 11 | rev | cut -f2 -d$'\t' -f 2 | rev | cut -w -f 3-
